### PR TITLE
Underlying TRNG C++ library updated to v4.23(.1)

### LINKED ISSUE #16: Valgrind issues on CRAN
[CRAN checks](https://cran.r-project.org/web/checks/check_results_rTRNG.html) for the released package version 4.20-1 reveals issues with `valgrind`, which should be investigated and fixed.

Note that a new submission fixing the issue has been requested by the CRAN Team **by 2021-01-29** in order to retain the package on CRAN

See comments below for the detailed investigation, which is summarized as follows:
- The issues reported by `valgrind` are all triggered by tests on errors when parsing an invalid string representation of a TRNG engine, which is pretty much a corner case we don't expect a typical user to hit.
- There is an easy fix that was successfully tested, it ~~is pretty unlikely we can~~ might not be viable to get a new (patched) version of the upstream TRNG C++ library as a new release by Jan 29. As an alternative, we should patch the version we include as part of rTRNG.
=> See https://github.com/miraisolutions/rTRNG/issues/16#issuecomment-767907113 for an explicit and reproducible approach for including a small patch on rTRNG side.
=> See https://github.com/miraisolutions/rTRNG/issues/16#issuecomment-768577382 and following comments regarding a proper fix in TRNG upstream.

Note: 
- We should upgrade to the new released TRNG available on GitHub as [v4.23 tag](https://github.com/rabauke/trng4/releases/tag/v4.23), see #18.
=> see below https://github.com/miraisolutions/rTRNG/issues/16#issuecomment-767858892

See #21 for the consolidation of the **upgrade to the patched upstream TRNG v4.23.1** into #20 on top of #18, including the introduction of `valgrind` checks via GitHub Actions

### PR DESCRIPTION
**Pull request by riccardoporreca**
See #18 for the intended upgrade to v4.23, and #21 for the the inclusion of the patch release v4.23.1, which fixes #16

In particular, the efforts described in #16 around reproducing and assessing `valgrind` issues based on the Docker image [wch1/r-debug](https://hub.docker.com/r/wch1/r-debug/) have been consolidated into a new GH actions workflow to automate such checks.

### CODE REVIEW

**Comment by riccardoporreca** [comment]
This also includes a small maintenance on the codecov side to align to the standard settings one would obtain with `usethis::use_coverage()`, which also make the coverage diff only informative (i.e. not shown as failures)

**Review by RolandASc — APPROVED** [review]
looks good to me

**Comment by riccardoporreca** [comment]
@RolandASc, I am going to integrate the changes done in a patch of TRNG 4.23 upstream (see https://github.com/miraisolutions/rTRNG/issues/16#issuecomment-769429098) in this branch, so we include the patched 4.23.1 in this upgrade

**Comment by riccardoporreca** [comment]
@RolandASc, I am going to merge this after including #21, I don't expect many functional aspects of the additional changed to be reviewed at this stage, and a final review will be done on `master` in preparation from the CRAN release.

**Pull request merged**
